site_name: Templado Documentation
site_description: Documentation for Templado 5.x
site_author: Arne Blankerts <arne@blankerts.de> and contributors
copyright: Copyright &copy; 2023, Arne Blankerts and contributors
site_url: https://docs.templado.io/
repo_url: https://github.com/templado/documentation
edit_uri: blob/main/src/
docs_dir: src
site_dir: build/public
nav:
  - Getting Started:
    - Installation: start/install.md
    - First Steps: start/start.md
  - Features:
      - View Model Rendering: features/viewmodel.md
      - Form Handling: features/forms.md
      - Merging Documents: features/merge.md
      - Applying Transformations: features/transformation.md
      - Controlling the Serializing: features/serializing.md
      - Filtering: features/filter.md
  - Extending Templado:
      - Creating Transformations: extend/transformations.md
      - Creating Filters: extend/filter.md
      - Creating Selectors: extend/selectors.md
      - Custom Serialization: extend/serializer.md
  - Migration:
      - Templado 4.x: migrate/templado4.md
  - Resources:
      - Project Homepage: https://templado.io
      - Source Code: https://github.com/templado/engine
      - Issue Tracker: https://github.com/templado/engine/issues
not_in_nav: |
  *index.md
theme:
  name: readthedocs
  highlightjs: false
  logo: img/templado-logo.svg
extra_css:
  - highlight/github.min.css
  - css/templado.css
extra_javascript:
  - highlight/highlight.min.js
  - highlight/all.js
markdown_extensions:
  - callouts
  - tables
plugins:
  - search
  - macros
